name: Test Pipeline

trigger: 
- main

variables:
  userName: Abhay 
  githubRegistry : https://github.com/Abhay189/Letter.git
  dockerImageName : letter-image
  dockerImageTag : $(Build.BuildId)

pool: 
  name: EC2-Agents

#Build the backend. Get the docker image. 
#Test the docker image with the testcases defined in django application 
#Deploy the docker image to the ACR.

stages:
- stage: ContainerBuild
  jobs:
    - job: Build 
      steps:
        # Setup docker on the Linux machine. 
        - task: DockerInstaller@0
          displayName: Install Docker 

        # Copy code registry to the linux server.
        # Build image on the linux machine. 

        - script: | 
            pwd 
            git clone $(githubRegistry)
            echo "Cloning is done"

            ls 

            echo "\n\n\n\n"
            docker build -t $(dockerImageName):$(dockerImageTag) ./Backend
            
            docker images

         



