trigger:
- main  

variables:
- group: letter-backend-variable-group 
- name: containerRegistry
  value: "letterregistry.azurecr.io"  
- name: imageTag
  value: "$(Build.BuildId)" 

stages:
- stage: Build
  displayName: Build Backend Image
  jobs:
  - job: BuildBackend
    displayName: Build Backend Docker Image
    pool:
      name: EC2-Agents
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker

    - script: |
        echo "Building Docker image..."
        docker build -t letter_backend ./Backend
        docker tag letter_backend $(containerRegistry)/letter_backend:$(imageTag)
      displayName: Build Docker Image


- stage: Test
  displayName: Test Backend Image
  dependsOn: Build
  jobs:
  - job: TestAPI
    displayName: Run API Tests
    pool:
      name: EC2-Agents
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker

    - script: |
        echo "Starting the backend container..."
        docker run -d --name backend_test -p 8000:8000 -e USE_SQLITE_FOR_TESTS=true $(containerRegistry)/letter_backend:$(imageTag)

        echo "Running Django tests..."
        docker exec backend_test python ./Backend/manage.py test chat.tests.test || { docker logs backend_test; docker stop backend_test; docker rm backend_test; exit 1; }

        echo "Stopping and cleaning up..."
        docker stop backend_test
        docker rm backend_test
      displayName: Run Django Test Cases