name: Test Pipeline

trigger: 
- main

variables:
  userName: Abhay 

pool: 
  name: EC2-Agents

stages:
- stage: Hello
  jobs:
    - job: HelloJob
      steps:
        - script: echo "Hello there from $(userName)"



