

trigger: 
- main

variables:
  envVariable: this is your vaiable 

pool: 
  name: EC2-Agents

stages:
- stage: Hello
  jobs:
    - job: HelloJob
      steps:
        - script: echo "hello Azure Devops!"



