version: '3.8'

services:
  mysql: 
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abhay532 
    volumes:
      - mysql-data:/var/lib/mysql  # Map a named volume to persist data

  backend:
    build:
      context: ./Backend  # Path to the backend Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql  # Start MySQL first
    volumes:
      - ./Backend:/app  # Bind mount for live development

  frontend:
    build:
      context: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app  # Syncs local files with the container
      - /app/node_modules  # Prevents node_modules conflicts
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables file change detection inside Docker

volumes:
  mysql-data: