# Generated by Django 5.1.1 on 2024-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_num",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
