# Generated by Django 5.1.1 on 2024-09-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_user_password_alter_user_phone_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
