# Generated by Django 5.1.1 on 2024-09-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_num",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
