# Generated by Django 5.1.1 on 2024-09-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_alter_user_phone_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_num",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
