# Generated by Django 5.1.1 on 2024-09-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messanger_app", "0003_alter_customuser_contacts_alter_customuser_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_data",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="contacts",
            field=models.ManyToManyField(to="messanger_app.customuser"),
        ),
    ]
