# Generated by Django 5.1.1 on 2024-09-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messanger_app", "0004_message_message_data_alter_customuser_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="messanger_app.customuser"),
        ),
    ]
